ALTER TABLE "availability" ALTER COLUMN "id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "availability" ALTER COLUMN "property_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "availability" ALTER COLUMN "user_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "communication_templates" ALTER COLUMN "id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "communication_templates" ALTER COLUMN "user_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "communications" ALTER COLUMN "id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "communications" ALTER COLUMN "user_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "communications" ALTER COLUMN "renter_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "communications" ALTER COLUMN "property_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "documents" ALTER COLUMN "id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "documents" ALTER COLUMN "user_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "documents" ALTER COLUMN "property_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "documents" ALTER COLUMN "renter_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "documents" ALTER COLUMN "lease_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "expenses" ALTER COLUMN "id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "expenses" ALTER COLUMN "property_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "expenses" ALTER COLUMN "user_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "leases" ALTER COLUMN "id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "leases" ALTER COLUMN "property_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "leases" ALTER COLUMN "renter_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "leases" ALTER COLUMN "user_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "maintenance_requests" ALTER COLUMN "id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "maintenance_requests" ALTER COLUMN "property_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "maintenance_requests" ALTER COLUMN "renter_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "maintenance_requests" ALTER COLUMN "user_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "payment_reminders" ALTER COLUMN "id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "payment_reminders" ALTER COLUMN "payment_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "payment_reminders" ALTER COLUMN "user_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "payments" ALTER COLUMN "id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "payments" ALTER COLUMN "lease_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "payments" ALTER COLUMN "user_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "properties" ALTER COLUMN "id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "properties" ALTER COLUMN "user_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "renters" ALTER COLUMN "id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "renters" ALTER COLUMN "user_id" SET DATA TYPE varchar(36);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "id" SET DATA TYPE varchar(36);